version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis-db
    ports:
      - "6379:6379"

  flask-app:
    build: .
    container_name: iss-tracker
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=iss_tracker.py

